// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/activity.dart';
import 'models/reward.dart';
import 'models/transaction.dart';
import 'models/user.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8378760439597630669),
    name: 'Activity',
    lastPropertyId: const obx_int.IdUid(6, 1403280911222085861),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7772246141248055056),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4080407065618840883),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4594496594359212475),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7513824692520123819),
        name: 'durationMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 27286234648009627),
        name: 'points',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1403280911222085861),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5487446234309648229),
    name: 'Reward',
    lastPropertyId: const obx_int.IdUid(5, 3914125864764322844),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7472004344713075909),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5499429455482712066),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3178946732621124752),
        name: 'pointCost',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8379259909218420528),
        name: 'progressPoints',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3914125864764322844),
        name: 'status',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 6377268452563949099),
    name: 'Transaction',
    lastPropertyId: const obx_int.IdUid(5, 6286497967629381569),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 610560911539123597),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2418023367115731835),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6049398446034040945),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7929448825758007320),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6286497967629381569),
        name: 'label',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 2329469739092839643),
    name: 'User',
    lastPropertyId: const obx_int.IdUid(9, 4748938019423360325),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1526713463288711543),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5746880915655654037),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 738847706527232748),
        name: 'pointBalance',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9080414185014505392),
        name: 'streak',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8242654423560653371),
        name: 'monthlyBudget',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6811716288641014415),
        name: 'burnoutScore',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4552032114663684726),
        name: 'adjustmentFactor',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6882565821372985067),
        name: 'disciplineScore',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4748938019423360325),
        name: 'lastActivityDate',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 2329469739092839643),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Activity: obx_int.EntityDefinition<Activity>(
      model: _entities[0],
      toOneRelations: (Activity object) => [],
      toManyRelations: (Activity object) => {},
      getId: (Activity object) => object.id,
      setId: (Activity object, int id) {
        object.id = id;
      },
      objectToFB: (Activity object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final categoryOffset = fbb.writeString(object.category);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, categoryOffset);
        fbb.addInt64(3, object.durationMinutes);
        fbb.addFloat64(4, object.points);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final durationMinutesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final pointsParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final object = Activity(
          id: idParam,
          title: titleParam,
          category: categoryParam,
          durationMinutes: durationMinutesParam,
          points: pointsParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
    Reward: obx_int.EntityDefinition<Reward>(
      model: _entities[1],
      toOneRelations: (Reward object) => [],
      toManyRelations: (Reward object) => {},
      getId: (Reward object) => object.id,
      setId: (Reward object, int id) {
        object.id = id;
      },
      objectToFB: (Reward object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final statusOffset = fbb.writeString(object.status);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addFloat64(2, object.pointCost);
        fbb.addFloat64(3, object.progressPoints);
        fbb.addOffset(4, statusOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final pointCostParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final progressPointsParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = Reward(
          id: idParam,
          name: nameParam,
          pointCost: pointCostParam,
          progressPoints: progressPointsParam,
          status: statusParam,
        );

        return object;
      },
    ),
    Transaction: obx_int.EntityDefinition<Transaction>(
      model: _entities[2],
      toOneRelations: (Transaction object) => [],
      toManyRelations: (Transaction object) => {},
      getId: (Transaction object) => object.id,
      setId: (Transaction object, int id) {
        object.id = id;
      },
      objectToFB: (Transaction object, fb.Builder fbb) {
        final typeOffset = fbb.writeString(object.type);
        final labelOffset = fbb.writeString(object.label);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, typeOffset);
        fbb.addFloat64(2, object.amount);
        fbb.addInt64(3, object.date.millisecondsSinceEpoch);
        fbb.addOffset(4, labelOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final dateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final labelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = Transaction(
          id: idParam,
          type: typeParam,
          amount: amountParam,
          date: dateParam,
          label: labelParam,
        );

        return object;
      },
    ),
    User: obx_int.EntityDefinition<User>(
      model: _entities[3],
      toOneRelations: (User object) => [],
      toManyRelations: (User object) => {},
      getId: (User object) => object.id,
      setId: (User object, int id) {
        object.id = id;
      },
      objectToFB: (User object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addFloat64(2, object.pointBalance);
        fbb.addInt64(3, object.streak);
        fbb.addFloat64(4, object.monthlyBudget);
        fbb.addFloat64(5, object.burnoutScore);
        fbb.addFloat64(6, object.adjustmentFactor);
        fbb.addFloat64(7, object.disciplineScore);
        fbb.addInt64(8, object.lastActivityDate.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final pointBalanceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final streakParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final monthlyBudgetParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final burnoutScoreParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final adjustmentFactorParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final disciplineScoreParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final lastActivityDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final object = User(
          id: idParam,
          name: nameParam,
          pointBalance: pointBalanceParam,
          streak: streakParam,
          monthlyBudget: monthlyBudgetParam,
          burnoutScore: burnoutScoreParam,
          adjustmentFactor: adjustmentFactorParam,
          disciplineScore: disciplineScoreParam,
          lastActivityDate: lastActivityDateParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Activity] entity fields to define ObjectBox queries.
class Activity_ {
  /// See [Activity.id].
  static final id = obx.QueryIntegerProperty<Activity>(
    _entities[0].properties[0],
  );

  /// See [Activity.title].
  static final title = obx.QueryStringProperty<Activity>(
    _entities[0].properties[1],
  );

  /// See [Activity.category].
  static final category = obx.QueryStringProperty<Activity>(
    _entities[0].properties[2],
  );

  /// See [Activity.durationMinutes].
  static final durationMinutes = obx.QueryIntegerProperty<Activity>(
    _entities[0].properties[3],
  );

  /// See [Activity.points].
  static final points = obx.QueryDoubleProperty<Activity>(
    _entities[0].properties[4],
  );

  /// See [Activity.createdAt].
  static final createdAt = obx.QueryDateProperty<Activity>(
    _entities[0].properties[5],
  );
}

/// [Reward] entity fields to define ObjectBox queries.
class Reward_ {
  /// See [Reward.id].
  static final id = obx.QueryIntegerProperty<Reward>(
    _entities[1].properties[0],
  );

  /// See [Reward.name].
  static final name = obx.QueryStringProperty<Reward>(
    _entities[1].properties[1],
  );

  /// See [Reward.pointCost].
  static final pointCost = obx.QueryDoubleProperty<Reward>(
    _entities[1].properties[2],
  );

  /// See [Reward.progressPoints].
  static final progressPoints = obx.QueryDoubleProperty<Reward>(
    _entities[1].properties[3],
  );

  /// See [Reward.status].
  static final status = obx.QueryStringProperty<Reward>(
    _entities[1].properties[4],
  );
}

/// [Transaction] entity fields to define ObjectBox queries.
class Transaction_ {
  /// See [Transaction.id].
  static final id = obx.QueryIntegerProperty<Transaction>(
    _entities[2].properties[0],
  );

  /// See [Transaction.type].
  static final type = obx.QueryStringProperty<Transaction>(
    _entities[2].properties[1],
  );

  /// See [Transaction.amount].
  static final amount = obx.QueryDoubleProperty<Transaction>(
    _entities[2].properties[2],
  );

  /// See [Transaction.date].
  static final date = obx.QueryDateProperty<Transaction>(
    _entities[2].properties[3],
  );

  /// See [Transaction.label].
  static final label = obx.QueryStringProperty<Transaction>(
    _entities[2].properties[4],
  );
}

/// [User] entity fields to define ObjectBox queries.
class User_ {
  /// See [User.id].
  static final id = obx.QueryIntegerProperty<User>(_entities[3].properties[0]);

  /// See [User.name].
  static final name = obx.QueryStringProperty<User>(_entities[3].properties[1]);

  /// See [User.pointBalance].
  static final pointBalance = obx.QueryDoubleProperty<User>(
    _entities[3].properties[2],
  );

  /// See [User.streak].
  static final streak = obx.QueryIntegerProperty<User>(
    _entities[3].properties[3],
  );

  /// See [User.monthlyBudget].
  static final monthlyBudget = obx.QueryDoubleProperty<User>(
    _entities[3].properties[4],
  );

  /// See [User.burnoutScore].
  static final burnoutScore = obx.QueryDoubleProperty<User>(
    _entities[3].properties[5],
  );

  /// See [User.adjustmentFactor].
  static final adjustmentFactor = obx.QueryDoubleProperty<User>(
    _entities[3].properties[6],
  );

  /// See [User.disciplineScore].
  static final disciplineScore = obx.QueryDoubleProperty<User>(
    _entities[3].properties[7],
  );

  /// See [User.lastActivityDate].
  static final lastActivityDate = obx.QueryDateProperty<User>(
    _entities[3].properties[8],
  );
}
