// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/activity.dart';
import 'data/models/activity_preset.dart';
import 'data/models/badge.dart';
import 'data/models/category.dart';
import 'data/models/game_event.dart';
import 'data/models/habit_stack.dart';
import 'data/models/quest.dart';
import 'data/models/reward.dart';
import 'data/models/season.dart';
import 'data/models/season_progress.dart';
import 'data/models/stack_item.dart';
import 'data/models/transaction.dart';
import 'data/models/user.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8378760439597630669),
    name: 'Activity',
    lastPropertyId: const obx_int.IdUid(7, 8269014644489575122),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7772246141248055056),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4080407065618840883),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7513824692520123819),
        name: 'durationMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 27286234648009627),
        name: 'points',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1403280911222085861),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8269014644489575122),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 3911332620656891733),
        relationTarget: 'Category',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5487446234309648229),
    name: 'Reward',
    lastPropertyId: const obx_int.IdUid(15, 5373135433765886221),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7472004344713075909),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5499429455482712066),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3178946732621124752),
        name: 'pointCost',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8379259909218420528),
        name: 'progressPoints',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3914125864764322844),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1282077585155473386),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1069163868834099856),
        name: 'iconEmoji',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8618466584560608699),
        name: 'recurrenceType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7204818839221795198),
        name: 'recurrenceIntervalDays',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7800174343127086709),
        name: 'monthlyLimit',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5642445334576474994),
        name: 'timesRedeemed',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 842377422317441525),
        name: 'lastRedeemedAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 809781644067206420),
        name: 'scheduledFor',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 2462667693307869165),
        name: 'isTemplate',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 5373135433765886221),
        name: 'isArchived',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 6377268452563949099),
    name: 'Transaction',
    lastPropertyId: const obx_int.IdUid(5, 6286497967629381569),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 610560911539123597),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2418023367115731835),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6049398446034040945),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7929448825758007320),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6286497967629381569),
        name: 'label',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 2329469739092839643),
    name: 'User',
    lastPropertyId: const obx_int.IdUid(21, 4372895117579580195),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1526713463288711543),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5746880915655654037),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 738847706527232748),
        name: 'pointBalance',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9080414185014505392),
        name: 'streak',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8242654423560653371),
        name: 'monthlyBudget',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6811716288641014415),
        name: 'burnoutScore',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4552032114663684726),
        name: 'adjustmentFactor',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6882565821372985067),
        name: 'disciplineScore',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4748938019423360325),
        name: 'lastActivityDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4169637164274842401),
        name: 'onboardingDone',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4428244356466403435),
        name: 'income',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 775868884036182860),
        name: 'rewardPercentage',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8683160586099615495),
        name: 'lastWeeklyAdjustmentDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 6799221967030747424),
        name: 'xp',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 4586355628929139878),
        name: 'dailyPointTarget',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 7455435355485559539),
        name: 'notificationsEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 2472654809828793826),
        name: 'preferredReminderHour',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 7775652137231328337),
        name: 'quietHoursStart',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 2220298126360873456),
        name: 'quietHoursEnd',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 6137839207692255229),
        name: 'restDayCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 4372895117579580195),
        name: 'lastRestDayDate',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 3322047366399380042),
    name: 'Badge',
    lastPropertyId: const obx_int.IdUid(10, 966599234471453781),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8153145288076872618),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2759936791084830019),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1793264907511378251),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1344440584892728241),
        name: 'icon',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5874067951615650337),
        name: 'unlockedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2262233366461776302),
        name: 'badgeKey',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 3333553318397306036),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6382925441357053053),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7449654561980373721),
        name: 'rarity',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 781843219672483026),
        name: 'isUnlocked',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 966599234471453781),
        name: 'conditionJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 2640218046937028971),
    name: 'Category',
    lastPropertyId: const obx_int.IdUid(5, 7265396781866812993),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4352459434270688408),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3149154721878129159),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3431854584732876063),
        name: 'weight',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7775013380014703493),
        name: 'isNegative',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7265396781866812993),
        name: 'icon',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 7567813523073515485),
    name: 'Quest',
    lastPropertyId: const obx_int.IdUid(15, 1537780824442832454),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7371158289919641552),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6040200239087109432),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2175402730683762936),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3127731869596257500),
        name: 'bonusPoints',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7426645031311613286),
        name: 'isCompleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3731154141248843751),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2267035780086213689),
        name: 'conditionType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7533677366773694261),
        name: 'conditionJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 8504469234203673709),
        name: 'rewardBadgeId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 4949161896773739033),
        name: 'expiresAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 8721969685919625293),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 1537780824442832454),
        name: 'progress',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 5845437736512944696),
    name: 'ActivityPreset',
    lastPropertyId: const obx_int.IdUid(5, 2134722590970084420),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5495318047791083633),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2676697481260441231),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6768655033661243172),
        name: 'durationMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4152633897801720380),
        name: 'isDefault',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2134722590970084420),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 3777624002170199725),
        relationTarget: 'Category',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 7808974247994837562),
    name: 'HabitStack',
    lastPropertyId: const obx_int.IdUid(7, 4820018273641208428),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4778114985009592970),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3205921390749209001),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4356225111457186785),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3620418212218115576),
        name: 'isTemplate',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8299000440384491623),
        name: 'bonusPoints',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 582442702901983559),
        name: 'streakDays',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4820018273641208428),
        name: 'lastCompletedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'items',
        srcEntity: 'StackItem',
        srcField: '',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 7342917611015812829),
    name: 'StackItem',
    lastPropertyId: const obx_int.IdUid(7, 6203203611291167830),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5979955306093983416),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 322927633571149786),
        name: 'activityTitle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 286723056455138777),
        name: 'durationMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4688313266828945134),
        name: 'order',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6550157265344477643),
        name: 'isCompleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8747843462921719409),
        name: 'stackId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 5598720275755946603),
        relationTarget: 'HabitStack',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6203203611291167830),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(5, 5555334313111654792),
        relationTarget: 'Category',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(11, 2557365640441454112),
    name: 'GameEvent',
    lastPropertyId: const obx_int.IdUid(9, 3180405990358567827),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8193640348775864306),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8151176896268184773),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4020750977805384163),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3721411005798409741),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5147108500045417948),
        name: 'multiplier',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4546513750729967413),
        name: 'startAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1562960696349937423),
        name: 'endAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5684525397656855590),
        name: 'isActive',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3180405990358567827),
        name: 'targetCategoryId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(12, 3765060305610154998),
    name: 'Season',
    lastPropertyId: const obx_int.IdUid(7, 6917089895121272658),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3419207769211005338),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7564926970231952667),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8230430264770792831),
        name: 'themeKey',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5923449641650617892),
        name: 'startAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2229340776866562236),
        name: 'endAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6652341584909128135),
        name: 'isActive',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6917089895121272658),
        name: 'milestonesJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(13, 6555632522327042793),
    name: 'SeasonProgress',
    lastPropertyId: const obx_int.IdUid(6, 1413626782031776680),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3200192800114898439),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8769422093713330127),
        name: 'seasonId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(6, 2854972863311880089),
        relationTarget: 'Season',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5562363865291043077),
        name: 'userId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(7, 4135129020907092117),
        relationTarget: 'User',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6257366229845059426),
        name: 'xpEarned',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1074105798098028902),
        name: 'rank',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1413626782031776680),
        name: 'milestoneReached',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(13, 6555632522327042793),
    lastIndexId: const obx_int.IdUid(7, 4135129020907092117),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      4594496594359212475,
      6070520624509161020,
      2990638843911408226,
      152670071877584968,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Activity: obx_int.EntityDefinition<Activity>(
      model: _entities[0],
      toOneRelations: (Activity object) => [object.category],
      toManyRelations: (Activity object) => {},
      getId: (Activity object) => object.id,
      setId: (Activity object, int id) {
        object.id = id;
      },
      objectToFB: (Activity object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addInt64(3, object.durationMinutes);
        fbb.addFloat64(4, object.points);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(6, object.category.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final durationMinutesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final pointsParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final object = Activity(
          id: idParam,
          title: titleParam,
          durationMinutes: durationMinutesParam,
          points: pointsParam,
          createdAt: createdAtParam,
        );
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        object.category.attach(store);
        return object;
      },
    ),
    Reward: obx_int.EntityDefinition<Reward>(
      model: _entities[1],
      toOneRelations: (Reward object) => [],
      toManyRelations: (Reward object) => {},
      getId: (Reward object) => object.id,
      setId: (Reward object, int id) {
        object.id = id;
      },
      objectToFB: (Reward object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final statusOffset = fbb.writeString(object.status);
        final categoryOffset = fbb.writeString(object.category);
        final iconEmojiOffset = fbb.writeString(object.iconEmoji);
        final recurrenceTypeOffset = fbb.writeString(object.recurrenceType);
        final lastRedeemedAtOffset = object.lastRedeemedAt == null
            ? null
            : fbb.writeString(object.lastRedeemedAt!);
        fbb.startTable(16);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addFloat64(2, object.pointCost);
        fbb.addFloat64(3, object.progressPoints);
        fbb.addOffset(4, statusOffset);
        fbb.addOffset(5, categoryOffset);
        fbb.addOffset(6, iconEmojiOffset);
        fbb.addOffset(7, recurrenceTypeOffset);
        fbb.addInt64(8, object.recurrenceIntervalDays);
        fbb.addInt64(9, object.monthlyLimit);
        fbb.addInt64(10, object.timesRedeemed);
        fbb.addOffset(11, lastRedeemedAtOffset);
        fbb.addInt64(12, object.scheduledFor?.millisecondsSinceEpoch);
        fbb.addBool(13, object.isTemplate);
        fbb.addBool(14, object.isArchived);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final scheduledForValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          28,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final pointCostParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final progressPointsParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final iconEmojiParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final recurrenceTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final recurrenceIntervalDaysParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 20);
        final monthlyLimitParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final timesRedeemedParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final lastRedeemedAtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final scheduledForParam = scheduledForValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(scheduledForValue);
        final isTemplateParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          30,
          false,
        );
        final isArchivedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          32,
          false,
        );
        final object = Reward(
          id: idParam,
          name: nameParam,
          pointCost: pointCostParam,
          progressPoints: progressPointsParam,
          status: statusParam,
          category: categoryParam,
          iconEmoji: iconEmojiParam,
          recurrenceType: recurrenceTypeParam,
          recurrenceIntervalDays: recurrenceIntervalDaysParam,
          monthlyLimit: monthlyLimitParam,
          timesRedeemed: timesRedeemedParam,
          lastRedeemedAt: lastRedeemedAtParam,
          scheduledFor: scheduledForParam,
          isTemplate: isTemplateParam,
          isArchived: isArchivedParam,
        );

        return object;
      },
    ),
    Transaction: obx_int.EntityDefinition<Transaction>(
      model: _entities[2],
      toOneRelations: (Transaction object) => [],
      toManyRelations: (Transaction object) => {},
      getId: (Transaction object) => object.id,
      setId: (Transaction object, int id) {
        object.id = id;
      },
      objectToFB: (Transaction object, fb.Builder fbb) {
        final typeOffset = fbb.writeString(object.type);
        final labelOffset = fbb.writeString(object.label);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, typeOffset);
        fbb.addFloat64(2, object.amount);
        fbb.addInt64(3, object.date.millisecondsSinceEpoch);
        fbb.addOffset(4, labelOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final dateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final labelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = Transaction(
          id: idParam,
          type: typeParam,
          amount: amountParam,
          date: dateParam,
          label: labelParam,
        );

        return object;
      },
    ),
    User: obx_int.EntityDefinition<User>(
      model: _entities[3],
      toOneRelations: (User object) => [],
      toManyRelations: (User object) => {},
      getId: (User object) => object.id,
      setId: (User object, int id) {
        object.id = id;
      },
      objectToFB: (User object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(22);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addFloat64(2, object.pointBalance);
        fbb.addInt64(3, object.streak);
        fbb.addFloat64(4, object.monthlyBudget);
        fbb.addFloat64(5, object.burnoutScore);
        fbb.addFloat64(6, object.adjustmentFactor);
        fbb.addFloat64(7, object.disciplineScore);
        fbb.addInt64(8, object.lastActivityDate.millisecondsSinceEpoch);
        fbb.addBool(9, object.onboardingDone);
        fbb.addFloat64(10, object.income);
        fbb.addFloat64(11, object.rewardPercentage);
        fbb.addInt64(
          12,
          object.lastWeeklyAdjustmentDate.millisecondsSinceEpoch,
        );
        fbb.addFloat64(13, object.xp);
        fbb.addFloat64(14, object.dailyPointTarget);
        fbb.addBool(15, object.notificationsEnabled);
        fbb.addInt64(16, object.preferredReminderHour);
        fbb.addInt64(17, object.quietHoursStart);
        fbb.addInt64(18, object.quietHoursEnd);
        fbb.addInt64(19, object.restDayCount);
        fbb.addInt64(20, object.lastRestDayDate.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final pointBalanceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final streakParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final monthlyBudgetParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final burnoutScoreParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final adjustmentFactorParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final disciplineScoreParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final xpParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          30,
          0,
        );
        final lastActivityDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final dailyPointTargetParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          32,
          0,
        );
        final onboardingDoneParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final incomeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final rewardPercentageParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final lastWeeklyAdjustmentDateParam =
            DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0),
            );
        final notificationsEnabledParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          34,
          false,
        );
        final preferredReminderHourParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          36,
          0,
        );
        final quietHoursStartParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          38,
          0,
        );
        final quietHoursEndParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          40,
          0,
        );
        final restDayCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          42,
          0,
        );
        final lastRestDayDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 44, 0),
        );
        final object = User(
          id: idParam,
          name: nameParam,
          pointBalance: pointBalanceParam,
          streak: streakParam,
          monthlyBudget: monthlyBudgetParam,
          burnoutScore: burnoutScoreParam,
          adjustmentFactor: adjustmentFactorParam,
          disciplineScore: disciplineScoreParam,
          xp: xpParam,
          lastActivityDate: lastActivityDateParam,
          dailyPointTarget: dailyPointTargetParam,
          onboardingDone: onboardingDoneParam,
          income: incomeParam,
          rewardPercentage: rewardPercentageParam,
          lastWeeklyAdjustmentDate: lastWeeklyAdjustmentDateParam,
          notificationsEnabled: notificationsEnabledParam,
          preferredReminderHour: preferredReminderHourParam,
          quietHoursStart: quietHoursStartParam,
          quietHoursEnd: quietHoursEndParam,
          restDayCount: restDayCountParam,
          lastRestDayDate: lastRestDayDateParam,
        );

        return object;
      },
    ),
    Badge: obx_int.EntityDefinition<Badge>(
      model: _entities[4],
      toOneRelations: (Badge object) => [],
      toManyRelations: (Badge object) => {},
      getId: (Badge object) => object.id,
      setId: (Badge object, int id) {
        object.id = id;
      },
      objectToFB: (Badge object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = fbb.writeString(object.description);
        final iconOffset = fbb.writeString(object.icon);
        final badgeKeyOffset = fbb.writeString(object.badgeKey);
        final categoryOffset = fbb.writeString(object.category);
        final conditionJsonOffset = fbb.writeString(object.conditionJson);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, iconOffset);
        fbb.addInt64(4, object.unlockedAt?.millisecondsSinceEpoch);
        fbb.addOffset(5, badgeKeyOffset);
        fbb.addOffset(6, categoryOffset);
        fbb.addInt64(7, object.rarity);
        fbb.addBool(8, object.isUnlocked);
        fbb.addOffset(9, conditionJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final unlockedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final badgeKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final iconParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final rarityParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final isUnlockedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final unlockedAtParam = unlockedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(unlockedAtValue);
        final conditionJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final object = Badge(
          id: idParam,
          badgeKey: badgeKeyParam,
          name: nameParam,
          description: descriptionParam,
          icon: iconParam,
          category: categoryParam,
          rarity: rarityParam,
          isUnlocked: isUnlockedParam,
          unlockedAt: unlockedAtParam,
          conditionJson: conditionJsonParam,
        );

        return object;
      },
    ),
    Category: obx_int.EntityDefinition<Category>(
      model: _entities[5],
      toOneRelations: (Category object) => [],
      toManyRelations: (Category object) => {},
      getId: (Category object) => object.id,
      setId: (Category object, int id) {
        object.id = id;
      },
      objectToFB: (Category object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final iconOffset = fbb.writeString(object.icon);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addFloat64(2, object.weight);
        fbb.addBool(3, object.isNegative);
        fbb.addOffset(4, iconOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final weightParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final isNegativeParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final iconParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = Category(
          id: idParam,
          name: nameParam,
          weight: weightParam,
          isNegative: isNegativeParam,
          icon: iconParam,
        );

        return object;
      },
    ),
    Quest: obx_int.EntityDefinition<Quest>(
      model: _entities[6],
      toOneRelations: (Quest object) => [],
      toManyRelations: (Quest object) => {},
      getId: (Quest object) => object.id,
      setId: (Quest object, int id) {
        object.id = id;
      },
      objectToFB: (Quest object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final descriptionOffset = fbb.writeString(object.description);
        final typeOffset = fbb.writeString(object.type);
        final conditionTypeOffset = fbb.writeString(object.conditionType);
        final conditionJsonOffset = fbb.writeString(object.conditionJson);
        final rewardBadgeIdOffset = object.rewardBadgeId == null
            ? null
            : fbb.writeString(object.rewardBadgeId!);
        fbb.startTable(16);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addFloat64(5, object.bonusPoints);
        fbb.addBool(6, object.isCompleted);
        fbb.addOffset(8, typeOffset);
        fbb.addOffset(9, conditionTypeOffset);
        fbb.addOffset(10, conditionJsonOffset);
        fbb.addOffset(11, rewardBadgeIdOffset);
        fbb.addInt64(12, object.expiresAt.millisecondsSinceEpoch);
        fbb.addInt64(13, object.createdAt.millisecondsSinceEpoch);
        fbb.addFloat64(14, object.progress);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final conditionTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final conditionJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final bonusPointsParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final rewardBadgeIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final expiresAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0),
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 30, 0),
        );
        final isCompletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final progressParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          32,
          0,
        );
        final object = Quest(
          id: idParam,
          title: titleParam,
          description: descriptionParam,
          type: typeParam,
          conditionType: conditionTypeParam,
          conditionJson: conditionJsonParam,
          bonusPoints: bonusPointsParam,
          rewardBadgeId: rewardBadgeIdParam,
          expiresAt: expiresAtParam,
          createdAt: createdAtParam,
          isCompleted: isCompletedParam,
          progress: progressParam,
        );

        return object;
      },
    ),
    ActivityPreset: obx_int.EntityDefinition<ActivityPreset>(
      model: _entities[7],
      toOneRelations: (ActivityPreset object) => [object.category],
      toManyRelations: (ActivityPreset object) => {},
      getId: (ActivityPreset object) => object.id,
      setId: (ActivityPreset object, int id) {
        object.id = id;
      },
      objectToFB: (ActivityPreset object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addInt64(2, object.durationMinutes);
        fbb.addBool(3, object.isDefault);
        fbb.addInt64(4, object.category.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final durationMinutesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final isDefaultParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final object = ActivityPreset(
          id: idParam,
          title: titleParam,
          durationMinutes: durationMinutesParam,
          isDefault: isDefaultParam,
        );
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.category.attach(store);
        return object;
      },
    ),
    HabitStack: obx_int.EntityDefinition<HabitStack>(
      model: _entities[8],
      toOneRelations: (HabitStack object) => [],
      toManyRelations: (HabitStack object) => {
        obx_int.RelInfo<StackItem>.toOneBacklink(
          6,
          object.id,
          (StackItem srcObject) => srcObject.stack,
        ): object.items,
      },
      getId: (HabitStack object) => object.id,
      setId: (HabitStack object, int id) {
        object.id = id;
      },
      objectToFB: (HabitStack object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = fbb.writeString(object.description);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addBool(3, object.isTemplate);
        fbb.addInt64(4, object.bonusPoints);
        fbb.addInt64(5, object.streakDays);
        fbb.addInt64(6, object.lastCompletedAt?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastCompletedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final isTemplateParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final bonusPointsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final streakDaysParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final lastCompletedAtParam = lastCompletedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastCompletedAtValue);
        final object = HabitStack(
          id: idParam,
          name: nameParam,
          description: descriptionParam,
          isTemplate: isTemplateParam,
          bonusPoints: bonusPointsParam,
          streakDays: streakDaysParam,
          lastCompletedAt: lastCompletedAtParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<HabitStack>(
          object.items,
          store,
          obx_int.RelInfo<StackItem>.toOneBacklink(
            6,
            object.id,
            (StackItem srcObject) => srcObject.stack,
          ),
        );
        return object;
      },
    ),
    StackItem: obx_int.EntityDefinition<StackItem>(
      model: _entities[9],
      toOneRelations: (StackItem object) => [object.stack, object.category],
      toManyRelations: (StackItem object) => {},
      getId: (StackItem object) => object.id,
      setId: (StackItem object, int id) {
        object.id = id;
      },
      objectToFB: (StackItem object, fb.Builder fbb) {
        final activityTitleOffset = fbb.writeString(object.activityTitle);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, activityTitleOffset);
        fbb.addInt64(2, object.durationMinutes);
        fbb.addInt64(3, object.order);
        fbb.addBool(4, object.isCompleted);
        fbb.addInt64(5, object.stack.targetId);
        fbb.addInt64(6, object.category.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final activityTitleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final durationMinutesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final orderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final isCompletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final object = StackItem(
          id: idParam,
          activityTitle: activityTitleParam,
          durationMinutes: durationMinutesParam,
          order: orderParam,
          isCompleted: isCompletedParam,
        );
        object.stack.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        object.stack.attach(store);
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        object.category.attach(store);
        return object;
      },
    ),
    GameEvent: obx_int.EntityDefinition<GameEvent>(
      model: _entities[10],
      toOneRelations: (GameEvent object) => [],
      toManyRelations: (GameEvent object) => {},
      getId: (GameEvent object) => object.id,
      setId: (GameEvent object, int id) {
        object.id = id;
      },
      objectToFB: (GameEvent object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = fbb.writeString(object.description);
        final typeOffset = fbb.writeString(object.type);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, typeOffset);
        fbb.addFloat64(4, object.multiplier);
        fbb.addInt64(5, object.startAt.millisecondsSinceEpoch);
        fbb.addInt64(6, object.endAt.millisecondsSinceEpoch);
        fbb.addBool(7, object.isActive);
        fbb.addInt64(8, object.targetCategoryId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final multiplierParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final startAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final endAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final isActiveParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final targetCategoryIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final object = GameEvent(
          id: idParam,
          name: nameParam,
          description: descriptionParam,
          type: typeParam,
          multiplier: multiplierParam,
          startAt: startAtParam,
          endAt: endAtParam,
          isActive: isActiveParam,
          targetCategoryId: targetCategoryIdParam,
        );

        return object;
      },
    ),
    Season: obx_int.EntityDefinition<Season>(
      model: _entities[11],
      toOneRelations: (Season object) => [],
      toManyRelations: (Season object) => {},
      getId: (Season object) => object.id,
      setId: (Season object, int id) {
        object.id = id;
      },
      objectToFB: (Season object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final themeKeyOffset = fbb.writeString(object.themeKey);
        final milestonesJsonOffset = fbb.writeString(object.milestonesJson);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, themeKeyOffset);
        fbb.addInt64(3, object.startAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.endAt.millisecondsSinceEpoch);
        fbb.addBool(5, object.isActive);
        fbb.addOffset(6, milestonesJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final themeKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final startAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final endAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final isActiveParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final milestonesJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final object = Season(
          id: idParam,
          name: nameParam,
          themeKey: themeKeyParam,
          startAt: startAtParam,
          endAt: endAtParam,
          isActive: isActiveParam,
          milestonesJson: milestonesJsonParam,
        );

        return object;
      },
    ),
    SeasonProgress: obx_int.EntityDefinition<SeasonProgress>(
      model: _entities[12],
      toOneRelations: (SeasonProgress object) => [object.season, object.user],
      toManyRelations: (SeasonProgress object) => {},
      getId: (SeasonProgress object) => object.id,
      setId: (SeasonProgress object, int id) {
        object.id = id;
      },
      objectToFB: (SeasonProgress object, fb.Builder fbb) {
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.season.targetId);
        fbb.addInt64(2, object.user.targetId);
        fbb.addFloat64(3, object.xpEarned);
        fbb.addInt64(4, object.rank);
        fbb.addInt64(5, object.milestoneReached);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final xpEarnedParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final rankParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final milestoneReachedParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = SeasonProgress(
          id: idParam,
          xpEarned: xpEarnedParam,
          rank: rankParam,
          milestoneReached: milestoneReachedParam,
        );
        object.season.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.season.attach(store);
        object.user.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.user.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Activity] entity fields to define ObjectBox queries.
class Activity_ {
  /// See [Activity.id].
  static final id = obx.QueryIntegerProperty<Activity>(
    _entities[0].properties[0],
  );

  /// See [Activity.title].
  static final title = obx.QueryStringProperty<Activity>(
    _entities[0].properties[1],
  );

  /// See [Activity.durationMinutes].
  static final durationMinutes = obx.QueryIntegerProperty<Activity>(
    _entities[0].properties[2],
  );

  /// See [Activity.points].
  static final points = obx.QueryDoubleProperty<Activity>(
    _entities[0].properties[3],
  );

  /// See [Activity.createdAt].
  static final createdAt = obx.QueryDateProperty<Activity>(
    _entities[0].properties[4],
  );

  /// See [Activity.category].
  static final category = obx.QueryRelationToOne<Activity, Category>(
    _entities[0].properties[5],
  );
}

/// [Reward] entity fields to define ObjectBox queries.
class Reward_ {
  /// See [Reward.id].
  static final id = obx.QueryIntegerProperty<Reward>(
    _entities[1].properties[0],
  );

  /// See [Reward.name].
  static final name = obx.QueryStringProperty<Reward>(
    _entities[1].properties[1],
  );

  /// See [Reward.pointCost].
  static final pointCost = obx.QueryDoubleProperty<Reward>(
    _entities[1].properties[2],
  );

  /// See [Reward.progressPoints].
  static final progressPoints = obx.QueryDoubleProperty<Reward>(
    _entities[1].properties[3],
  );

  /// See [Reward.status].
  static final status = obx.QueryStringProperty<Reward>(
    _entities[1].properties[4],
  );

  /// See [Reward.category].
  static final category = obx.QueryStringProperty<Reward>(
    _entities[1].properties[5],
  );

  /// See [Reward.iconEmoji].
  static final iconEmoji = obx.QueryStringProperty<Reward>(
    _entities[1].properties[6],
  );

  /// See [Reward.recurrenceType].
  static final recurrenceType = obx.QueryStringProperty<Reward>(
    _entities[1].properties[7],
  );

  /// See [Reward.recurrenceIntervalDays].
  static final recurrenceIntervalDays = obx.QueryIntegerProperty<Reward>(
    _entities[1].properties[8],
  );

  /// See [Reward.monthlyLimit].
  static final monthlyLimit = obx.QueryIntegerProperty<Reward>(
    _entities[1].properties[9],
  );

  /// See [Reward.timesRedeemed].
  static final timesRedeemed = obx.QueryIntegerProperty<Reward>(
    _entities[1].properties[10],
  );

  /// See [Reward.lastRedeemedAt].
  static final lastRedeemedAt = obx.QueryStringProperty<Reward>(
    _entities[1].properties[11],
  );

  /// See [Reward.scheduledFor].
  static final scheduledFor = obx.QueryDateProperty<Reward>(
    _entities[1].properties[12],
  );

  /// See [Reward.isTemplate].
  static final isTemplate = obx.QueryBooleanProperty<Reward>(
    _entities[1].properties[13],
  );

  /// See [Reward.isArchived].
  static final isArchived = obx.QueryBooleanProperty<Reward>(
    _entities[1].properties[14],
  );
}

/// [Transaction] entity fields to define ObjectBox queries.
class Transaction_ {
  /// See [Transaction.id].
  static final id = obx.QueryIntegerProperty<Transaction>(
    _entities[2].properties[0],
  );

  /// See [Transaction.type].
  static final type = obx.QueryStringProperty<Transaction>(
    _entities[2].properties[1],
  );

  /// See [Transaction.amount].
  static final amount = obx.QueryDoubleProperty<Transaction>(
    _entities[2].properties[2],
  );

  /// See [Transaction.date].
  static final date = obx.QueryDateProperty<Transaction>(
    _entities[2].properties[3],
  );

  /// See [Transaction.label].
  static final label = obx.QueryStringProperty<Transaction>(
    _entities[2].properties[4],
  );
}

/// [User] entity fields to define ObjectBox queries.
class User_ {
  /// See [User.id].
  static final id = obx.QueryIntegerProperty<User>(_entities[3].properties[0]);

  /// See [User.name].
  static final name = obx.QueryStringProperty<User>(_entities[3].properties[1]);

  /// See [User.pointBalance].
  static final pointBalance = obx.QueryDoubleProperty<User>(
    _entities[3].properties[2],
  );

  /// See [User.streak].
  static final streak = obx.QueryIntegerProperty<User>(
    _entities[3].properties[3],
  );

  /// See [User.monthlyBudget].
  static final monthlyBudget = obx.QueryDoubleProperty<User>(
    _entities[3].properties[4],
  );

  /// See [User.burnoutScore].
  static final burnoutScore = obx.QueryDoubleProperty<User>(
    _entities[3].properties[5],
  );

  /// See [User.adjustmentFactor].
  static final adjustmentFactor = obx.QueryDoubleProperty<User>(
    _entities[3].properties[6],
  );

  /// See [User.disciplineScore].
  static final disciplineScore = obx.QueryDoubleProperty<User>(
    _entities[3].properties[7],
  );

  /// See [User.lastActivityDate].
  static final lastActivityDate = obx.QueryDateProperty<User>(
    _entities[3].properties[8],
  );

  /// See [User.onboardingDone].
  static final onboardingDone = obx.QueryBooleanProperty<User>(
    _entities[3].properties[9],
  );

  /// See [User.income].
  static final income = obx.QueryDoubleProperty<User>(
    _entities[3].properties[10],
  );

  /// See [User.rewardPercentage].
  static final rewardPercentage = obx.QueryDoubleProperty<User>(
    _entities[3].properties[11],
  );

  /// See [User.lastWeeklyAdjustmentDate].
  static final lastWeeklyAdjustmentDate = obx.QueryDateProperty<User>(
    _entities[3].properties[12],
  );

  /// See [User.xp].
  static final xp = obx.QueryDoubleProperty<User>(_entities[3].properties[13]);

  /// See [User.dailyPointTarget].
  static final dailyPointTarget = obx.QueryDoubleProperty<User>(
    _entities[3].properties[14],
  );

  /// See [User.notificationsEnabled].
  static final notificationsEnabled = obx.QueryBooleanProperty<User>(
    _entities[3].properties[15],
  );

  /// See [User.preferredReminderHour].
  static final preferredReminderHour = obx.QueryIntegerProperty<User>(
    _entities[3].properties[16],
  );

  /// See [User.quietHoursStart].
  static final quietHoursStart = obx.QueryIntegerProperty<User>(
    _entities[3].properties[17],
  );

  /// See [User.quietHoursEnd].
  static final quietHoursEnd = obx.QueryIntegerProperty<User>(
    _entities[3].properties[18],
  );

  /// See [User.restDayCount].
  static final restDayCount = obx.QueryIntegerProperty<User>(
    _entities[3].properties[19],
  );

  /// See [User.lastRestDayDate].
  static final lastRestDayDate = obx.QueryDateProperty<User>(
    _entities[3].properties[20],
  );
}

/// [Badge] entity fields to define ObjectBox queries.
class Badge_ {
  /// See [Badge.id].
  static final id = obx.QueryIntegerProperty<Badge>(_entities[4].properties[0]);

  /// See [Badge.name].
  static final name = obx.QueryStringProperty<Badge>(
    _entities[4].properties[1],
  );

  /// See [Badge.description].
  static final description = obx.QueryStringProperty<Badge>(
    _entities[4].properties[2],
  );

  /// See [Badge.icon].
  static final icon = obx.QueryStringProperty<Badge>(
    _entities[4].properties[3],
  );

  /// See [Badge.unlockedAt].
  static final unlockedAt = obx.QueryDateProperty<Badge>(
    _entities[4].properties[4],
  );

  /// See [Badge.badgeKey].
  static final badgeKey = obx.QueryStringProperty<Badge>(
    _entities[4].properties[5],
  );

  /// See [Badge.category].
  static final category = obx.QueryStringProperty<Badge>(
    _entities[4].properties[6],
  );

  /// See [Badge.rarity].
  static final rarity = obx.QueryIntegerProperty<Badge>(
    _entities[4].properties[7],
  );

  /// See [Badge.isUnlocked].
  static final isUnlocked = obx.QueryBooleanProperty<Badge>(
    _entities[4].properties[8],
  );

  /// See [Badge.conditionJson].
  static final conditionJson = obx.QueryStringProperty<Badge>(
    _entities[4].properties[9],
  );
}

/// [Category] entity fields to define ObjectBox queries.
class Category_ {
  /// See [Category.id].
  static final id = obx.QueryIntegerProperty<Category>(
    _entities[5].properties[0],
  );

  /// See [Category.name].
  static final name = obx.QueryStringProperty<Category>(
    _entities[5].properties[1],
  );

  /// See [Category.weight].
  static final weight = obx.QueryDoubleProperty<Category>(
    _entities[5].properties[2],
  );

  /// See [Category.isNegative].
  static final isNegative = obx.QueryBooleanProperty<Category>(
    _entities[5].properties[3],
  );

  /// See [Category.icon].
  static final icon = obx.QueryStringProperty<Category>(
    _entities[5].properties[4],
  );
}

/// [Quest] entity fields to define ObjectBox queries.
class Quest_ {
  /// See [Quest.id].
  static final id = obx.QueryIntegerProperty<Quest>(_entities[6].properties[0]);

  /// See [Quest.title].
  static final title = obx.QueryStringProperty<Quest>(
    _entities[6].properties[1],
  );

  /// See [Quest.description].
  static final description = obx.QueryStringProperty<Quest>(
    _entities[6].properties[2],
  );

  /// See [Quest.bonusPoints].
  static final bonusPoints = obx.QueryDoubleProperty<Quest>(
    _entities[6].properties[3],
  );

  /// See [Quest.isCompleted].
  static final isCompleted = obx.QueryBooleanProperty<Quest>(
    _entities[6].properties[4],
  );

  /// See [Quest.type].
  static final type = obx.QueryStringProperty<Quest>(
    _entities[6].properties[5],
  );

  /// See [Quest.conditionType].
  static final conditionType = obx.QueryStringProperty<Quest>(
    _entities[6].properties[6],
  );

  /// See [Quest.conditionJson].
  static final conditionJson = obx.QueryStringProperty<Quest>(
    _entities[6].properties[7],
  );

  /// See [Quest.rewardBadgeId].
  static final rewardBadgeId = obx.QueryStringProperty<Quest>(
    _entities[6].properties[8],
  );

  /// See [Quest.expiresAt].
  static final expiresAt = obx.QueryDateProperty<Quest>(
    _entities[6].properties[9],
  );

  /// See [Quest.createdAt].
  static final createdAt = obx.QueryDateProperty<Quest>(
    _entities[6].properties[10],
  );

  /// See [Quest.progress].
  static final progress = obx.QueryDoubleProperty<Quest>(
    _entities[6].properties[11],
  );
}

/// [ActivityPreset] entity fields to define ObjectBox queries.
class ActivityPreset_ {
  /// See [ActivityPreset.id].
  static final id = obx.QueryIntegerProperty<ActivityPreset>(
    _entities[7].properties[0],
  );

  /// See [ActivityPreset.title].
  static final title = obx.QueryStringProperty<ActivityPreset>(
    _entities[7].properties[1],
  );

  /// See [ActivityPreset.durationMinutes].
  static final durationMinutes = obx.QueryIntegerProperty<ActivityPreset>(
    _entities[7].properties[2],
  );

  /// See [ActivityPreset.isDefault].
  static final isDefault = obx.QueryBooleanProperty<ActivityPreset>(
    _entities[7].properties[3],
  );

  /// See [ActivityPreset.category].
  static final category = obx.QueryRelationToOne<ActivityPreset, Category>(
    _entities[7].properties[4],
  );
}

/// [HabitStack] entity fields to define ObjectBox queries.
class HabitStack_ {
  /// See [HabitStack.id].
  static final id = obx.QueryIntegerProperty<HabitStack>(
    _entities[8].properties[0],
  );

  /// See [HabitStack.name].
  static final name = obx.QueryStringProperty<HabitStack>(
    _entities[8].properties[1],
  );

  /// See [HabitStack.description].
  static final description = obx.QueryStringProperty<HabitStack>(
    _entities[8].properties[2],
  );

  /// See [HabitStack.isTemplate].
  static final isTemplate = obx.QueryBooleanProperty<HabitStack>(
    _entities[8].properties[3],
  );

  /// See [HabitStack.bonusPoints].
  static final bonusPoints = obx.QueryIntegerProperty<HabitStack>(
    _entities[8].properties[4],
  );

  /// See [HabitStack.streakDays].
  static final streakDays = obx.QueryIntegerProperty<HabitStack>(
    _entities[8].properties[5],
  );

  /// See [HabitStack.lastCompletedAt].
  static final lastCompletedAt = obx.QueryDateProperty<HabitStack>(
    _entities[8].properties[6],
  );

  /// see [HabitStack.items]
  static final items = obx.QueryBacklinkToMany<StackItem, HabitStack>(
    StackItem_.stack,
  );
}

/// [StackItem] entity fields to define ObjectBox queries.
class StackItem_ {
  /// See [StackItem.id].
  static final id = obx.QueryIntegerProperty<StackItem>(
    _entities[9].properties[0],
  );

  /// See [StackItem.activityTitle].
  static final activityTitle = obx.QueryStringProperty<StackItem>(
    _entities[9].properties[1],
  );

  /// See [StackItem.durationMinutes].
  static final durationMinutes = obx.QueryIntegerProperty<StackItem>(
    _entities[9].properties[2],
  );

  /// See [StackItem.order].
  static final order = obx.QueryIntegerProperty<StackItem>(
    _entities[9].properties[3],
  );

  /// See [StackItem.isCompleted].
  static final isCompleted = obx.QueryBooleanProperty<StackItem>(
    _entities[9].properties[4],
  );

  /// See [StackItem.stack].
  static final stack = obx.QueryRelationToOne<StackItem, HabitStack>(
    _entities[9].properties[5],
  );

  /// See [StackItem.category].
  static final category = obx.QueryRelationToOne<StackItem, Category>(
    _entities[9].properties[6],
  );
}

/// [GameEvent] entity fields to define ObjectBox queries.
class GameEvent_ {
  /// See [GameEvent.id].
  static final id = obx.QueryIntegerProperty<GameEvent>(
    _entities[10].properties[0],
  );

  /// See [GameEvent.name].
  static final name = obx.QueryStringProperty<GameEvent>(
    _entities[10].properties[1],
  );

  /// See [GameEvent.description].
  static final description = obx.QueryStringProperty<GameEvent>(
    _entities[10].properties[2],
  );

  /// See [GameEvent.type].
  static final type = obx.QueryStringProperty<GameEvent>(
    _entities[10].properties[3],
  );

  /// See [GameEvent.multiplier].
  static final multiplier = obx.QueryDoubleProperty<GameEvent>(
    _entities[10].properties[4],
  );

  /// See [GameEvent.startAt].
  static final startAt = obx.QueryDateProperty<GameEvent>(
    _entities[10].properties[5],
  );

  /// See [GameEvent.endAt].
  static final endAt = obx.QueryDateProperty<GameEvent>(
    _entities[10].properties[6],
  );

  /// See [GameEvent.isActive].
  static final isActive = obx.QueryBooleanProperty<GameEvent>(
    _entities[10].properties[7],
  );

  /// See [GameEvent.targetCategoryId].
  static final targetCategoryId = obx.QueryIntegerProperty<GameEvent>(
    _entities[10].properties[8],
  );
}

/// [Season] entity fields to define ObjectBox queries.
class Season_ {
  /// See [Season.id].
  static final id = obx.QueryIntegerProperty<Season>(
    _entities[11].properties[0],
  );

  /// See [Season.name].
  static final name = obx.QueryStringProperty<Season>(
    _entities[11].properties[1],
  );

  /// See [Season.themeKey].
  static final themeKey = obx.QueryStringProperty<Season>(
    _entities[11].properties[2],
  );

  /// See [Season.startAt].
  static final startAt = obx.QueryDateProperty<Season>(
    _entities[11].properties[3],
  );

  /// See [Season.endAt].
  static final endAt = obx.QueryDateProperty<Season>(
    _entities[11].properties[4],
  );

  /// See [Season.isActive].
  static final isActive = obx.QueryBooleanProperty<Season>(
    _entities[11].properties[5],
  );

  /// See [Season.milestonesJson].
  static final milestonesJson = obx.QueryStringProperty<Season>(
    _entities[11].properties[6],
  );
}

/// [SeasonProgress] entity fields to define ObjectBox queries.
class SeasonProgress_ {
  /// See [SeasonProgress.id].
  static final id = obx.QueryIntegerProperty<SeasonProgress>(
    _entities[12].properties[0],
  );

  /// See [SeasonProgress.season].
  static final season = obx.QueryRelationToOne<SeasonProgress, Season>(
    _entities[12].properties[1],
  );

  /// See [SeasonProgress.user].
  static final user = obx.QueryRelationToOne<SeasonProgress, User>(
    _entities[12].properties[2],
  );

  /// See [SeasonProgress.xpEarned].
  static final xpEarned = obx.QueryDoubleProperty<SeasonProgress>(
    _entities[12].properties[3],
  );

  /// See [SeasonProgress.rank].
  static final rank = obx.QueryIntegerProperty<SeasonProgress>(
    _entities[12].properties[4],
  );

  /// See [SeasonProgress.milestoneReached].
  static final milestoneReached = obx.QueryIntegerProperty<SeasonProgress>(
    _entities[12].properties[5],
  );
}
